name: ✨ Feature Request  
description: 新機能や改善の提案
title: "[FEATURE] "
labels: ["enhancement", "needs-discussion"]
body:
  - type: markdown
    attributes:
      value: |
        新機能のアイデアをありがとうございます！🎉
        ChromaDB MCP Serverをより良くするために、詳細を教えてください。

  - type: textarea
    id: feature-summary
    attributes:
      label: ✨ 機能の概要
      description: 実装したい機能を簡潔に説明してください
      placeholder: ChromaDB君が...できるようになると良いと思います
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 🎯 動機・背景
      description: なぜこの機能が必要だと思うか教えてください
      placeholder: 現在...で困っているため、...があると便利だと思います
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 解決策の提案
      description: どのように実装すべきかのアイデアがあれば教えてください
      placeholder: ...のような機能を追加して...

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 代替案
      description: 他に考えられる解決方法があれば教えてください
      placeholder: または...という方法もあるかもしれません

  - type: dropdown
    id: priority
    attributes:
      label: 📊 優先度
      description: この機能の重要度はどの程度ですか？
      options:
        - Low (あると便利)
        - Medium (結構重要)
        - High (かなり重要)
        - Critical (緊急に必要)
    validations:
      required: true

  - type: checkboxes
    id: feature-category
    attributes:
      label: 🏷️ 機能カテゴリ（該当するものをチェック）
      options:
        - label: 🩺 ChromaDBケア・健康管理機能
        - label: 🔍 検索・分析機能
        - label: 🛠️ 運用・メンテナンス機能
        - label: 📊 監視・ログ機能
        - label: 🌐 API・インターフェース
        - label: 📚 ドキュメント・ヘルプ
        - label: 🎨 UI・UX改善
        - label: ⚡ パフォーマンス向上
        - label: 🔒 セキュリティ・安全性
        - label: 🧪 テスト・品質向上

  - type: textarea
    id: additional-context
    attributes:
      label: 📎 追加情報
      description: その他、機能実装に役立ちそうな情報があれば教えてください
      placeholder: 参考リンク、類似機能の例など

  - type: checkboxes
    id: contribution
    attributes:
      label: 🤝 貢献意思
      description: この機能の実装に協力していただけますか？
      options:
        - label: アイデア提供のみ
        - label: 設計・仕様策定に協力可能
        - label: 実装・コーディングに協力可能
        - label: テスト・検証に協力可能
        - label: ドキュメント作成に協力可能
