# ChromaDB MCP サーバー設定ファイル

# ChromaDB設定
chromadb:
  collection: "sister_chat_history_v4"
  # 以下はオプション設定（必要に応じて有効化）
  # host: "localhost"  # リモートChromaDBを使用する場合
  # port: 8000        # リモートChromaDBのポート

# ログ設定
logging:
  level: "INFO"       # DEBUG, INFO, WARNING, ERROR
  file: "mcp_server.log"

# サーバー設定
server:
  name: "chromadb-mcp-server"
  # tools:
  #   - capture_conversation  # 会話キャプチャツール
  #   - search_knowledge      # 知識検索ツール
